version: '2'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: project/__init__.py
      SQL_HOST: db
      SQL_PORT: 3306
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app -w 4
    ports:
      - 5050:5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --slow_query_log=on --long_query_time=5 --slow_query_log_file=slow.log
    ports:
      - 3306:3306
    volumes:
      - ./scripts/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data/mysql:/var/lib/mysql

#  elasticsearch:
#    build: ./services/elasticsearch/
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: logstash:7.16.1
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./services/logstash/config:/etc/logstash/conf.d
      - ./data/mysql/slow.log:/logs/slow.log
    ports:
      - "5000:5000"
      - "5044:5044"
#    depends_on:
#      - elasticsearch

#  kibana:
#    build: ./services/kibana/
#    volumes:
#      - ./services/kibana/config/:/opt/kibana/config/
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch

  filebeat:
    image: prameswar/filebeat
    volumes:
      - ./services/filebeat/config:/etc/filebeat
      - ./data/mysql/slow.log:/logs/slow.log
#    depends_on:
#      - elasticsearch



